import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
interface GeneralSettings {
  businessName: string;
}

async function getGeneralSettings(): Promise<GeneralSettings> {
  // Use an absolute URL pointing to our running dev server.
  // The empty `{}` for the second argument tells Next.js to use its default caching,
  // which can be invalidated by the "Publish" button.
  const res = await fetch(`${process.env.NEXT_PUBLIC_SITE_URL}/api/content/general`, {});
  const data = await res.json();
  return data.json;
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const settings = await getGeneralSettings();

  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="bg-gray-100 p-4 flex justify-between items-center shadow-md">
          <div>
            <Link href="/" className="font-bold text-xl text-pink-600 hover:text-pink-700">
              {settings.businessName}
            </Link>
          </div>
          <div className="flex gap-8">
            <Link href="/menu" className="text-gray-700 hover:text-black font-medium">
              Menu
            </Link>
            <Link href="/events" className="text-gray-700 hover:text-black font-medium">
              Events
            </Link>
            <Link href="/contact" className="text-gray-700 hover:text-black font-medium">
              Contact
            </Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
